# Generated by ChatGPT on 2026-01-29
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models
import uuid


def _thumb_upload_path(instance, filename):
    return f"component_thumbs/{instance.created_at.strftime('%Y%m') if instance.created_at else 'unknown'}/{filename}"


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComponentLibraryItem",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("template_id", models.CharField(max_length=200, unique=True, db_index=True)),
                ("name", models.CharField(max_length=200, db_index=True)),
                ("template", models.JSONField()),
                ("schema_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                ("thumb_asset_id", models.CharField(max_length=200, null=True, blank=True)),
                ("thumb_file", models.FileField(upload_to=_thumb_upload_path, null=True, blank=True)),
            ],
            options={"ordering": ["-saved_at"]},
        )
    ]
