# Generated by Django 4.2.11 on 2026-01-29 00:14

from django.db import migrations, models
import dvs_editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('dvs_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentlibraryitem',
            name='thumb_file',
            field=models.FileField(blank=True, null=True, upload_to=dvs_editor.models._thumb_upload_path),
        ),
    ]
