# Generated by Django 4.2.11 on 2026-06-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comfyui_bridge', '0008_videogenerationtaskmirror_download_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationTaskMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_task_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider', models.CharField(blank=True, db_index=True, default='seedance', max_length=32)),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('task_type', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, default='bottom-chat', max_length=32)),
                ('status', models.CharField(blank=True, db_index=True, default='queued', max_length=32)),
                ('prompt', models.TextField(blank=True, default='')),
                ('ratio', models.CharField(blank=True, default='', max_length=32)),
                ('resolution', models.CharField(blank=True, default='', max_length=32)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('generate_audio', models.BooleanField(default=False)),
                ('watermark', models.BooleanField(default=False)),
                ('camera_fixed', models.BooleanField(default=False)),
                ('service_tier', models.CharField(blank=True, default='', max_length=32)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('video_url_remote', models.CharField(blank=True, default='', max_length=1000)),
                ('video_url_local', models.CharField(blank=True, default='', max_length=1000)),
                ('video_source_path_local', models.CharField(blank=True, default='', max_length=1000)),
                ('last_frame_url_remote', models.CharField(blank=True, default='', max_length=1000)),
                ('last_frame_url_local', models.CharField(blank=True, default='', max_length=1000)),
                ('last_frame_source_path_local', models.CharField(blank=True, default='', max_length=1000)),
                ('download_status', models.CharField(blank=True, db_index=True, default='idle', max_length=32)),
                ('download_progress', models.PositiveIntegerField(default=0)),
                ('download_error', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('status_text', models.TextField(blank=True, default='')),
                ('remote_created_at', models.BigIntegerField(blank=True, null=True)),
                ('remote_updated_at', models.BigIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_video_generation_tasks', to='comfyui_bridge.blueprintproject')),
            ],
            options={
                'db_table': 'third_party_video_generation_task_mirror',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeshyTaskMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('mode', models.CharField(blank=True, default='', max_length=48)),
                ('task_target', models.CharField(blank=True, default='', max_length=16)),
                ('task_family', models.CharField(blank=True, default='', max_length=48)),
                ('relation_kind', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('root_task_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('parent_task_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, db_index=True, default='idle', max_length=32)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=1000)),
                ('preferred_model_url', models.CharField(blank=True, default='', max_length=1000)),
                ('local_asset_url', models.CharField(blank=True, default='', max_length=1000)),
                ('local_asset_path', models.CharField(blank=True, default='', max_length=1000)),
                ('source_model_url', models.CharField(blank=True, default='', max_length=1000)),
                ('error_message', models.TextField(blank=True, default='')),
                ('status_text', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_node_id', models.CharField(blank=True, default='', max_length=128)),
                ('remote_created_at', models.CharField(blank=True, default='', max_length=64)),
                ('remote_finished_at', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_meshy_tasks', to='comfyui_bridge.blueprintproject')),
            ],
            options={
                'db_table': 'third_party_meshy_task_mirror',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
