# Generated by GitHub Copilot on 2026-02-23
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKeySecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("deepseek", "DeepSeek"), ("gemini", "Gemini")], max_length=32, unique=True)),
                ("key_encrypted", models.TextField(blank=True, default="")),
                (
                    "key_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="sha256 fingerprint of the plaintext key for UI/status only (not reversible)",
                        max_length=64,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dweb_api_key_secret",
            },
        ),
    ]
