# Generated by GitHub Copilot on 2026-03-02
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dwebapp", "0001_api_key_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikeysecret",
            name="provider",
            field=models.CharField(
                choices=[
                    ("deepseek", "DeepSeek"),
                    ("gemini", "Gemini"),
                    ("bytedance", "字节跳动(方舟)"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
