<template>
	<Transition name="tsd-dialog">
		<div
			v-if="open"
			class="tsd-mask"
			data-bp-ui-overlay="true"
			@pointerdown.stop
			@mousedown.stop
			@contextmenu.prevent.stop
			@click.self="handleCancel"
		>
			<div
				class="tsd-dialog"
				data-bp-ui-overlay="true"
				@pointerdown.stop
				@mousedown.stop
				@click.stop
				@contextmenu.prevent.stop
			>
				<div class="tsd-bg-layer" aria-hidden="true">
					<div class="tsd-bg-gradient"></div>
					<div class="tsd-bg-grid"></div>
				</div>
				<div class="tsd-scanline" aria-hidden="true"></div>
				<div class="sq-container tsd-particles" aria-hidden="true">
					<span v-for="p in particles" :key="p.id" class="sq-particle" :style="p.style"></span>
				</div>
				<span class="tsd-corner tsd-corner-tl" aria-hidden="true"></span>
				<span class="tsd-corner tsd-corner-tr" aria-hidden="true"></span>
				<span class="tsd-corner tsd-corner-bl" aria-hidden="true"></span>
				<span class="tsd-corner tsd-corner-br" aria-hidden="true"></span>

				<div class="tsd-header">
					<div class="tsd-title-wrap">
						<div class="tsd-title">{{ dialogTitle }}</div>
						<div class="tsd-title-sub">{{ dialogSubtitle }}</div>
					</div>
					<button class="tsd-btn tsd-btn-icon tsd-btn-close" type="button" @click="handleCancel">
						<svg viewBox="0 0 16 16" width="18" height="18" aria-hidden="true">
							<path
								d="M4 4l8 8M12 4l-8 8"
								stroke="currentColor"
								stroke-width="1.5"
								stroke-linecap="round"
							/>
						</svg>
					</button>
				</div>

				<div class="tsd-body">
					<div class="tsd-form-row tsd-cover-row">
						<div class="tsd-label">{{ t('aiworkflow.templateCenter.templateCover') }}</div>
						<div class="tsd-cover-preview-wrap">
							<div class="tsd-cover-preview" @click="triggerCoverUpload">
								<img v-if="previewCoverUrl" :src="previewCoverUrl" alt="" class="tsd-cover-img" />
								<div v-else class="tsd-cover-placeholder">
									<svg viewBox="0 0 48 48" width="32" height="32" aria-hidden="true">
										<rect
											x="10"
											y="8"
											width="28"
											height="32"
											rx="1"
											fill="none"
											stroke="currentColor"
											stroke-width="1.2"
											opacity="0.4"
										/>
										<path
											d="M10 28l8-8 10 10 10-10"
											fill="none"
											stroke="currentColor"
											stroke-width="1.2"
											opacity="0.4"
											stroke-linecap="round"
										/>
										<circle
											cx="19"
											cy="19"
											r="3.5"
											fill="none"
											stroke="currentColor"
											stroke-width="1.2"
											opacity="0.4"
										/>
									</svg>
									<span>{{ t('aiworkflow.templateCenter.uploadCover') }}</span>
								</div>
							</div>
							<div class="tsd-cover-actions">
								<label class="tsd-btn tsd-btn-sm" :class="{ active: isAutoCover }">
									<input
										type="radio"
										name="coverMode"
										:checked="isAutoCover"
										@change="() => (isAutoCover = true)"
										class="tsd-sr-only"
									/>
									{{ t('aiworkflow.templateCenter.coverAutoGenerated') }}
								</label>
								<label class="tsd-btn tsd-btn-sm" :class="{ active: !isAutoCover }">
									<input
										type="radio"
										name="coverMode"
										:checked="!isAutoCover"
										@change="() => (isAutoCover = false)"
										class="tsd-sr-only"
									/>
									{{ t('aiworkflow.templateCenter.customCover') }}
								</label>
								<button
									v-if="!isAutoCover && customCoverBlob"
									class="tsd-btn tsd-btn-sm tsd-btn-ghost"
									type="button"
									@click="clearCustomCover"
								>
									{{ t('aiworkflow.templateCenter.resetCover') }}
								</button>
								<input
									ref="coverInputRef"
									type="file"
									accept="image/*"
									class="tsd-sr-only"
									@change="onCoverSelected"
								/>
							</div>
							<p class="tsd-hint">{{ t('aiworkflow.templateCenter.coverHint') }}</p>
						</div>
					</div>

					<div class="tsd-form-row">
						<label class="tsd-label" for="tsd-name">
							{{ t('aiworkflow.templateCenter.templateName') }}
						</label>
						<input
							id="tsd-name"
							v-model="form.name"
							class="tsd-input"
							type="text"
							:placeholder="t('aiworkflow.templateCenter.templateNamePlaceholder')"
							@keydown.enter.prevent="handleConfirm"
						/>
					</div>

					<div class="tsd-form-row">
						<label class="tsd-label" for="tsd-desc">
							{{ t('aiworkflow.templateCenter.templateDescription') }}
						</label>
						<textarea
							id="tsd-desc"
							v-model="form.description"
							class="tsd-textarea"
							:placeholder="t('aiworkflow.templateCenter.templateDescriptionPlaceholder')"
							rows="3"
						></textarea>
					</div>

					<div class="tsd-form-row">
						<label class="tsd-label" for="tsd-cat">
							{{ t('aiworkflow.templateCenter.templateCategory') }}
						</label>
						<select id="tsd-cat" v-model="form.category" class="tsd-select">
							<option value="basic">{{ t('aiworkflow.templateCategory.basic') }}</option>
							<option value="video-generation">
								{{ t('aiworkflow.templateCategory.video-generation') }}
							</option>
							<option value="image-to-video">
								{{ t('aiworkflow.templateCategory.image-to-video') }}
							</option>
							<option value="text-to-image">
								{{ t('aiworkflow.templateCategory.text-to-image') }}
							</option>
							<option value="model3d">{{ t('aiworkflow.templateCategory.model3d') }}</option>
							<option value="comfyui">{{ t('aiworkflow.templateCategory.comfyui') }}</option>
							<option value="other">{{ t('aiworkflow.templateCategory.other') }}</option>
						</select>
					</div>

					<div class="tsd-form-row">
						<div class="tsd-label">{{ t('aiworkflow.templateCenter.templateTags') }}</div>
						<div class="tsd-tag-input-wrap">
							<div v-if="form.tags.length > 0" class="tsd-tag-list">
								<span v-for="(tag, idx) in form.tags" :key="idx" class="tsd-tag-chip">
									{{ tag }}
									<button class="tsd-tag-remove" type="button" @click="removeTag(idx)">
										<svg viewBox="0 0 16 16" width="10" height="10" aria-hidden="true">
											<path
												d="M4 4l8 8M12 4l-8 8"
												stroke="currentColor"
												stroke-width="1.5"
												stroke-linecap="round"
											/>
										</svg>
									</button>
								</span>
							</div>
							<input
								v-model="tagInput"
								class="tsd-tag-input"
								type="text"
								:placeholder="t('aiworkflow.templateCenter.templateTagsPlaceholder')"
								@keydown.enter.prevent="addTag"
								@keydown.space.prevent="addTag"
								@keydown.backspace="onTagBackspace"
							/>
						</div>
						<p class="tsd-hint">{{ t('aiworkflow.templateCenter.tagsHint') }}</p>
					</div>
				</div>

				<div class="tsd-footer">
					<div class="tsd-footer-info">
						<template v-if="isSaving">
							<span>{{ t('aiworkflow.templateCenter.packingTemplate') }}</span>
						</template>
						<template v-else-if="props.scope === 'selection'">
							{{
								t('aiworkflow.templateCenter.savingSelection', {
									count: props.nodeIds?.length || 0
								})
							}}
						</template>
						<template v-else>
							{{ t('aiworkflow.templateCenter.savingFull', { count: nodeCount }) }}
						</template>
					</div>
					<div v-if="isSaving" class="tsd-progress-wrap">
						<div class="tsd-progress-bar">
							<div class="tsd-progress-fill" :style="{ width: progressPercent + '%' }"></div>
						</div>
						<span class="tsd-progress-text">{{ progressPercent }}%</span>
					</div>
					<div v-else class="tsd-footer-actions">
						<button class="tsd-btn tsd-btn-ghost" type="button" @click="handleCancel">
							{{ t('aiworkflow.templateCenter.cancel') }}
						</button>
						<button
							class="tsd-btn tsd-btn-primary"
							type="button"
							:disabled="isSaving"
							@click="handleConfirm"
						>
							<svg viewBox="0 0 16 16" width="13" height="13" aria-hidden="true">
								<path
									d="M3 8.5l3 3L13 5"
									fill="none"
									stroke="currentColor"
									stroke-width="1.6"
									stroke-linecap="round"
									stroke-linejoin="round"
								/>
							</svg>
							{{ t('aiworkflow.templateCenter.confirm') }}
						</button>
					</div>
				</div>
			</div>
		</div>
	</Transition>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { buildSquareParticles } from '../../composables/useSquareParticles'
import { useI18n } from '../../i18n'
import type { TemplateCategory } from '../../aiworkflow/template/types'

export interface SaveTemplateConfirmPayload {
	name: string
	description?: string
	category: TemplateCategory
	tags?: string[]
	scope: 'full' | 'selection'
	nodeIds?: string[]
	coverBlob: Blob | null
}

export interface SaveTemplateProgress {
	percent: number
	detail?: string
}

const props = withDefaults(
	defineProps<{
		open: boolean
		scope: 'full' | 'selection'
		nodeIds?: string[]
		nodeCount?: number
		prefillName?: string
		autoCoverBlob?: Blob | null
		saving?: boolean
		progress?: number
	}>(),
	{
		nodeCount: 0,
		prefillName: '',
		autoCoverBlob: null,
		saving: false,
		progress: 0
	}
)

const emit = defineEmits<{
	(e: 'update:open', value: boolean): void
	(e: 'confirm', payload: SaveTemplateConfirmPayload): void
}>()

const { t } = useI18n()

const particles = buildSquareParticles({ count: 8, seed: 777, baseOpacity: 0.3 })

const form = ref({
	name: '',
	description: '',
	category: 'other' as TemplateCategory,
	tags: [] as string[]
})
const tagInput = ref('')
const isAutoCover = ref(true)
const customCoverBlob = ref<Blob | null>(null)
const previewCoverUrl = ref<string>('')
const coverInputRef = ref<HTMLInputElement | null>(null)

const isSaving = computed(() => props.saving)
const progressPercent = computed(() => Math.min(100, Math.max(0, Math.round(props.progress || 0))))

const dialogTitle = computed(() =>
	props.scope === 'selection'
		? t('aiworkflow.templateCenter.saveSelectionAsTemplate')
		: t('aiworkflow.templateCenter.saveFullAsTemplate')
)
const dialogSubtitle = computed(() =>
	props.scope === 'selection'
		? t('aiworkflow.templateCenter.saveSelectionSubtitle')
		: t('aiworkflow.templateCenter.saveFullSubtitle')
)

const nodeCount = computed(() => {
	if (props.scope === 'selection') return props.nodeIds?.length || 0
	return props.nodeCount || 0
})

function resetForm() {
	form.value = {
		name: props.prefillName || '',
		description: '',
		category: 'other',
		tags: []
	}
	tagInput.value = ''
	isAutoCover.value = true
	clearCustomCover()
}

function clearCustomCover() {
	customCoverBlob.value = null
	if (previewCoverUrl.value) {
		URL.revokeObjectURL(previewCoverUrl.value)
		previewCoverUrl.value = ''
	}
	if (coverInputRef.value) {
		coverInputRef.value.value = ''
	}
}

function triggerCoverUpload() {
	if (!isAutoCover.value && coverInputRef.value) {
		coverInputRef.value.click()
	}
}

function onCoverSelected(e: Event) {
	const input = e.target as HTMLInputElement
	const file = input.files?.[0]
	if (!file) return
	if (!file.type.startsWith('image/')) return

	customCoverBlob.value = file
	if (previewCoverUrl.value) URL.revokeObjectURL(previewCoverUrl.value)
	previewCoverUrl.value = URL.createObjectURL(file)
}

function addTag() {
	const tag = tagInput.value.trim().replace(/[,，;；]/g, '')
	if (tag && !form.value.tags.includes(tag) && form.value.tags.length < 10) {
		form.value.tags.push(tag)
	}
	tagInput.value = ''
}

function removeTag(idx: number) {
	form.value.tags.splice(idx, 1)
}

function onTagBackspace(e: KeyboardEvent) {
	if (tagInput.value === '' && form.value.tags.length > 0) {
		form.value.tags.pop()
	}
}

function validate() {
	if (!form.value.name.trim()) return false
	return true
}

function handleConfirm() {
	if (isSaving.value) return
	if (tagInput.value.trim()) addTag()
	if (!validate()) return

	const coverBlob = isAutoCover.value ? props.autoCoverBlob : customCoverBlob.value
	emit('confirm', {
		name: form.value.name.trim(),
		description: form.value.description.trim() || undefined,
		category: form.value.category,
		tags: form.value.tags.length > 0 ? [...form.value.tags] : undefined,
		scope: props.scope,
		nodeIds: props.scope === 'selection' ? props.nodeIds : undefined,
		coverBlob: coverBlob || null
	})
}

function handleCancel() {
	if (isSaving.value) return
	emit('update:open', false)
}

watch(
	() => props.open,
	(val) => {
		if (val) {
			resetForm()
		} else {
			clearCustomCover()
		}
	},
	{ immediate: true }
)

watch(
	() => props.autoCoverBlob,
	(blob) => {
		if (blob && isAutoCover.value) {
			if (previewCoverUrl.value && !customCoverBlob.value)
				URL.revokeObjectURL(previewCoverUrl.value)
			previewCoverUrl.value = URL.createObjectURL(blob)
		} else if (!customCoverBlob.value && previewCoverUrl.value) {
			URL.revokeObjectURL(previewCoverUrl.value)
			previewCoverUrl.value = ''
		}
	},
	{ immediate: true }
)

watch(isAutoCover, (val) => {
	if (val) {
		if (props.autoCoverBlob) {
			if (previewCoverUrl.value && !customCoverBlob.value)
				URL.revokeObjectURL(previewCoverUrl.value)
			previewCoverUrl.value = URL.createObjectURL(props.autoCoverBlob)
		}
	} else {
		if (!customCoverBlob.value) {
			if (previewCoverUrl.value) URL.revokeObjectURL(previewCoverUrl.value)
			previewCoverUrl.value = ''
		}
	}
})

onBeforeUnmount(() => {
	clearCustomCover()
})
</script>

<style scoped>
@import '../../styles/square-particles.css';

.tsd-sr-only {
	position: absolute;
	width: 1px;
	height: 1px;
	padding: 0;
	margin: -1px;
	overflow: hidden;
	clip: rect(0, 0, 0, 0);
	white-space: nowrap;
	border: 0;
}

.tsd-mask {
	position: fixed;
	inset: 0;
	z-index: 2200;
	display: flex;
	align-items: center;
	justify-content: center;
	background: rgba(0, 0, 0, 0.55);
	backdrop-filter: blur(6px);
	padding: 24px;
	box-sizing: border-box;
	pointer-events: auto;
}

.tsd-dialog {
	--tsd-accent: var(--theme-accent, #1f9d84);
	--tsd-accent-hover: var(--theme-accent-hover, #27b99c);
	--tsd-cold: #3aa8b4;
	--tsd-fg: var(--theme-text-primary, #eaf2f5);
	--tsd-fg-soft: var(--theme-text-secondary, #9aa0a6);
	--tsd-bg-0: #07090d;
	--tsd-bg-1: #111a22;
	--tsd-input-border: color-mix(in srgb, var(--tsd-accent) 28%, transparent);
	position: relative;
	width: 100%;
	max-width: 560px;
	max-height: 90vh;
	display: flex;
	flex-direction: column;
	border: 1px solid color-mix(in srgb, var(--tsd-accent) 35%, transparent);
	border-radius: 2px;
	overflow: hidden;
	box-shadow:
		0 24px 80px rgba(0, 0, 0, 0.55),
		0 0 0 1px color-mix(in srgb, var(--tsd-accent) 15%, transparent),
		0 0 60px color-mix(in srgb, var(--tsd-accent) 10%, transparent);
	user-select: text;
}

.tsd-bg-layer {
	position: absolute;
	inset: 0;
	z-index: 0;
	pointer-events: none;
	overflow: hidden;
}

.tsd-bg-gradient {
	position: absolute;
	inset: 0;
	background:
		radial-gradient(
			ellipse 70% 50% at 80% 10%,
			color-mix(in srgb, var(--tsd-accent) 10%, transparent),
			transparent 60%
		),
		radial-gradient(
			ellipse 60% 50% at 10% 90%,
			color-mix(in srgb, var(--tsd-cold) 8%, transparent),
			transparent 55%
		),
		linear-gradient(180deg, var(--tsd-bg-0) 0%, var(--tsd-bg-1) 100%);
}

.tsd-bg-grid {
	position: absolute;
	inset: 0;
	background-image:
		linear-gradient(
			to right,
			color-mix(in srgb, var(--tsd-accent) 4%, transparent) 1px,
			transparent 1px
		),
		linear-gradient(
			to bottom,
			color-mix(in srgb, var(--tsd-accent) 4%, transparent) 1px,
			transparent 1px
		);
	background-size: 32px 32px;
	opacity: 0.35;
	mask-image: radial-gradient(ellipse at 50% 30%, #000 40%, transparent 100%);
	-webkit-mask-image: radial-gradient(ellipse at 50% 30%, #000 40%, transparent 100%);
}

.tsd-scanline {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	height: 1px;
	z-index: 1;
	background: linear-gradient(
		90deg,
		transparent 0%,
		color-mix(in srgb, var(--tsd-accent) 50%, transparent) 50%,
		transparent 100%
	);
	box-shadow: 0 0 10px color-mix(in srgb, var(--tsd-accent) 35%, transparent);
	pointer-events: none;
}

.tsd-particles {
	z-index: 2;
}

.tsd-corner {
	position: absolute;
	width: 14px;
	height: 14px;
	z-index: 10;
	pointer-events: none;
	border-color: var(--tsd-accent);
	border-style: solid;
	border-width: 0;
	opacity: 0.8;
}

.tsd-corner-tl {
	top: 6px;
	left: 6px;
	border-top-width: 2px;
	border-left-width: 2px;
}
.tsd-corner-tr {
	top: 6px;
	right: 6px;
	border-top-width: 2px;
	border-right-width: 2px;
}
.tsd-corner-bl {
	bottom: 6px;
	left: 6px;
	border-bottom-width: 2px;
	border-left-width: 2px;
}
.tsd-corner-br {
	bottom: 6px;
	right: 6px;
	border-bottom-width: 2px;
	border-right-width: 2px;
}

/* Header */
.tsd-header {
	position: relative;
	z-index: 5;
	display: flex;
	align-items: flex-start;
	justify-content: space-between;
	padding: 18px 24px 14px;
	border-bottom: 1px solid color-mix(in srgb, var(--tsd-accent) 20%, transparent);
	flex-shrink: 0;
}

.tsd-title-wrap {
	display: flex;
	flex-direction: column;
	gap: 4px;
}

.tsd-title {
	font-size: 18px;
	font-weight: 700;
	color: var(--tsd-fg);
	text-shadow: 0 0 12px color-mix(in srgb, var(--tsd-accent) 25%, transparent);
	letter-spacing: 0.02em;
}

.tsd-title-sub {
	font-size: 11px;
	color: var(--tsd-fg-soft);
	display: flex;
	align-items: center;
	gap: 6px;
}
.tsd-title-sub::before {
	content: '';
	display: inline-block;
	width: 5px;
	height: 5px;
	background: var(--tsd-accent);
	box-shadow: 0 0 6px var(--tsd-accent);
}

/* Body */
.tsd-body {
	position: relative;
	z-index: 5;
	flex: 1;
	overflow-y: auto;
	padding: 18px 24px;
	display: flex;
	flex-direction: column;
	gap: 14px;
}

.tsd-form-row {
	display: flex;
	flex-direction: column;
	gap: 6px;
}

.tsd-cover-row {
	gap: 8px;
}

.tsd-label {
	font-size: 12px;
	font-weight: 500;
	color: var(--tsd-fg);
	letter-spacing: 0.02em;
	display: flex;
	align-items: center;
	gap: 4px;
}

.tsd-input,
.tsd-textarea,
.tsd-select {
	width: 100%;
	padding: 8px 12px;
	border: 1px solid var(--tsd-input-border);
	border-radius: 2px;
	background: color-mix(in srgb, var(--tsd-fg) 3%, transparent);
	color: var(--tsd-fg);
	font-size: 13px;
	outline: none;
	box-sizing: border-box;
	transition:
		border-color 200ms ease,
		background 200ms ease,
		box-shadow 200ms ease;
	font-family: inherit;
	line-height: 1.5;
}

.tsd-input::placeholder,
.tsd-textarea::placeholder {
	color: color-mix(in srgb, var(--tsd-fg-soft) 60%, transparent);
}

.tsd-input:focus,
.tsd-textarea:focus,
.tsd-select:focus {
	border-color: color-mix(in srgb, var(--tsd-accent) 65%, transparent);
	background: color-mix(in srgb, var(--tsd-fg) 5%, transparent);
	box-shadow:
		0 0 0 1px color-mix(in srgb, var(--tsd-accent) 25%, transparent),
		0 0 14px color-mix(in srgb, var(--tsd-accent) 10%, transparent);
}

.tsd-textarea {
	resize: vertical;
	min-height: 64px;
}

.tsd-select {
	appearance: none;
	padding-right: 28px;
	background-color: color-mix(in srgb, var(--tsd-fg) 3%, transparent);
	background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 10 10'%3E%3Cpath d='M2 3.5L5 6.5L8 3.5' stroke='%239aa0a6' stroke-width='1.2' fill='none' stroke-linecap='round'/%3E%3C/svg%3E");
	background-repeat: no-repeat;
	background-position: right 10px center;
	background-size: 10px 10px;
	cursor: pointer;
}

.tsd-select option {
	background: var(--tsd-bg-1);
	color: var(--tsd-fg);
}

/* Cover */
.tsd-cover-preview-wrap {
	display: flex;
	flex-direction: column;
	gap: 8px;
}

.tsd-cover-preview {
	width: 200px;
	aspect-ratio: 16/10;
	border: 1px dashed color-mix(in srgb, var(--tsd-accent) 35%, transparent);
	border-radius: 2px;
	overflow: hidden;
	cursor: pointer;
	flex-shrink: 0;
	position: relative;
	background: color-mix(in srgb, var(--tsd-accent) 3%, #0a0e14);
	transition:
		border-color 200ms ease,
		box-shadow 200ms ease;
}

.tsd-cover-preview:hover {
	border-color: color-mix(in srgb, var(--tsd-accent) 65%, transparent);
	box-shadow: 0 0 12px color-mix(in srgb, var(--tsd-accent) 12%, transparent);
}

.tsd-cover-img {
	width: 100%;
	height: 100%;
	object-fit: cover;
	display: block;
}

.tsd-cover-placeholder {
	position: absolute;
	inset: 0;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	gap: 6px;
	color: var(--tsd-fg-soft);
	font-size: 11px;
}

.tsd-cover-actions {
	display: flex;
	gap: 6px;
	flex-wrap: wrap;
}

.tsd-hint {
	margin: 0;
	font-size: 11px;
	color: var(--tsd-fg-soft);
	opacity: 0.7;
}

/* Tags */
.tsd-tag-input-wrap {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	gap: 5px;
	padding: 5px 8px;
	border: 1px solid var(--tsd-input-border);
	border-radius: 2px;
	background: color-mix(in srgb, var(--tsd-fg) 3%, transparent);
	min-height: 36px;
	box-sizing: border-box;
	transition:
		border-color 200ms ease,
		box-shadow 200ms ease;
}

.tsd-tag-input-wrap:focus-within {
	border-color: color-mix(in srgb, var(--tsd-accent) 65%, transparent);
	box-shadow:
		0 0 0 1px color-mix(in srgb, var(--tsd-accent) 25%, transparent),
		0 0 14px color-mix(in srgb, var(--tsd-accent) 10%, transparent);
}

.tsd-tag-list {
	display: flex;
	flex-wrap: wrap;
	gap: 4px;
}

.tsd-tag-chip {
	display: inline-flex;
	align-items: center;
	gap: 4px;
	padding: 2px 8px;
	font-size: 11px;
	color: color-mix(in srgb, var(--tsd-accent) 85%, var(--tsd-fg));
	background: color-mix(in srgb, var(--tsd-accent) 10%, transparent);
	border: 1px solid color-mix(in srgb, var(--tsd-accent) 20%, transparent);
	border-radius: 2px;
	line-height: 1.5;
}

.tsd-tag-remove {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	width: 14px;
	height: 14px;
	padding: 0;
	border: none;
	border-radius: 50%;
	background: transparent;
	color: inherit;
	cursor: pointer;
	opacity: 0.6;
	transition:
		opacity 150ms ease,
		background 150ms ease;
}

.tsd-tag-remove:hover {
	opacity: 1;
	background: color-mix(in srgb, var(--tsd-accent) 20%, transparent);
}

.tsd-tag-input {
	flex: 1;
	min-width: 80px;
	border: none;
	outline: none;
	background: transparent;
	color: var(--tsd-fg);
	font-size: 12px;
	padding: 2px 0;
	font-family: inherit;
}

.tsd-tag-input::placeholder {
	color: color-mix(in srgb, var(--tsd-fg-soft) 50%, transparent);
}

/* Buttons */
.tsd-btn {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	gap: 6px;
	padding: 7px 14px;
	border: 1px solid color-mix(in srgb, var(--tsd-accent) 35%, transparent);
	background: color-mix(in srgb, var(--tsd-fg) 3%, transparent);
	color: var(--tsd-fg);
	font-size: 12px;
	letter-spacing: 0.02em;
	cursor: pointer;
	border-radius: 2px;
	transition:
		background 200ms ease,
		border-color 200ms ease,
		box-shadow 200ms ease,
		transform 160ms ease;
	font-family: inherit;
	white-space: nowrap;
	user-select: none;
}

.tsd-btn:hover {
	background: color-mix(in srgb, var(--tsd-accent) 10%, transparent);
	border-color: color-mix(in srgb, var(--tsd-accent) 55%, transparent);
	box-shadow: 0 0 12px color-mix(in srgb, var(--tsd-accent) 18%, transparent);
}

.tsd-btn:active {
	transform: translateY(1px);
}

.tsd-btn-primary {
	background: color-mix(in srgb, var(--tsd-accent) 15%, transparent);
	border-color: color-mix(in srgb, var(--tsd-accent) 55%, transparent);
	color: var(--tsd-accent);
	font-weight: 600;
}

.tsd-btn-primary:hover {
	background: var(--tsd-accent);
	border-color: var(--tsd-accent);
	color: #fff;
	box-shadow: 0 0 16px color-mix(in srgb, var(--tsd-accent) 28%, transparent);
}

.tsd-btn-ghost {
	background: transparent;
	border-color: color-mix(in srgb, var(--tsd-fg-soft) 30%, transparent);
	color: var(--tsd-fg-soft);
}

.tsd-btn-ghost:hover {
	border-color: color-mix(in srgb, var(--tsd-fg) 30%, transparent);
	color: var(--tsd-fg);
	background: color-mix(in srgb, var(--tsd-fg) 4%, transparent);
	box-shadow: none;
}

.tsd-btn-sm {
	padding: 4px 10px;
	font-size: 11px;
}

.tsd-btn.active {
	background: color-mix(in srgb, var(--tsd-accent) 15%, transparent);
	border-color: color-mix(in srgb, var(--tsd-accent) 50%, transparent);
	color: var(--tsd-accent);
}

.tsd-btn-icon {
	width: 32px;
	height: 32px;
	padding: 0;
}

.tsd-btn-close:hover {
	color: var(--tsd-accent);
}

/* Footer */
.tsd-footer {
	position: relative;
	z-index: 5;
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 14px 24px;
	border-top: 1px solid color-mix(in srgb, var(--tsd-accent) 20%, transparent);
	flex-shrink: 0;
	gap: 12px;
}

.tsd-footer-info {
	font-size: 11px;
	color: var(--tsd-fg-soft);
}

.tsd-footer-actions {
	display: flex;
	gap: 8px;
}

.tsd-progress-wrap {
	display: flex;
	align-items: center;
	gap: 10px;
	flex: 1;
	max-width: 280px;
}

.tsd-progress-bar {
	flex: 1;
	height: 6px;
	border-radius: 3px;
	background: color-mix(in srgb, var(--tsd-fg) 8%, transparent);
	overflow: hidden;
}

.tsd-progress-fill {
	height: 100%;
	border-radius: 3px;
	background: linear-gradient(90deg, var(--tsd-accent), var(--tsd-cold, #3aa8b4));
	transition: width 200ms ease;
	box-shadow: 0 0 8px color-mix(in srgb, var(--tsd-accent) 40%, transparent);
}

.tsd-progress-text {
	font-size: 11px;
	color: var(--tsd-accent);
	font-weight: 600;
	min-width: 36px;
	text-align: right;
	font-variant-numeric: tabular-nums;
}

.tsd-btn:disabled {
	opacity: 0.5;
	cursor: not-allowed;
	pointer-events: none;
}

/* Transition */
.tsd-dialog-enter-active,
.tsd-dialog-leave-active {
	transition:
		opacity 220ms ease,
		transform 220ms cubic-bezier(0.22, 0.61, 0.36, 1);
}

.tsd-dialog-enter-from,
.tsd-dialog-leave-to {
	opacity: 0;
	transform: scale(0.97) translateY(8px);
}

/* Reduced motion */
@media (prefers-reduced-motion: reduce) {
	.tsd-dialog-enter-active,
	.tsd-dialog-leave-active {
		transition: opacity 150ms ease;
	}
	.tsd-dialog-enter-from,
	.tsd-dialog-leave-to {
		transform: none;
	}
	.tsd-btn,
	.tsd-input,
	.tsd-textarea,
	.tsd-select,
	.tsd-tag-input-wrap,
	.tsd-cover-preview,
	.tsd-tag-remove {
		transition: none !important;
	}
	.tsd-btn:active {
		transform: none;
	}
}
</style>

<style>
/* Light theme — global (unscoped) to guarantee cascade works */
[data-theme='light'] .tsd-mask {
	background: rgba(180, 190, 200, 0.45) !important;
	backdrop-filter: blur(8px);
}
[data-theme='light'] .tsd-dialog {
	--tsd-bg-0: #eef2f5 !important;
	--tsd-bg-1: #dfe5eb !important;
	--tsd-fg: #1a1d21 !important;
	--tsd-fg-soft: #4a5058 !important;
	--tsd-input-border: rgba(31, 157, 132, 0.25) !important;
	background: transparent;
	border-color: rgba(31, 157, 132, 0.3) !important;
	box-shadow:
		0 24px 80px rgba(0, 0, 0, 0.15),
		0 0 0 1px rgba(31, 157, 132, 0.12),
		0 0 40px rgba(31, 157, 132, 0.08) !important;
}
[data-theme='light'] .tsd-bg-gradient {
	background:
		radial-gradient(ellipse 70% 50% at 80% 10%, rgba(31, 157, 132, 0.07), transparent 60%),
		radial-gradient(ellipse 60% 50% at 10% 90%, rgba(58, 168, 180, 0.05), transparent 55%),
		linear-gradient(180deg, #f0f3f6 0%, #dde3ea 100%) !important;
}
[data-theme='light'] .tsd-bg-grid {
	opacity: 0.22 !important;
	background-image:
		linear-gradient(to right, rgba(31, 157, 132, 0.05) 1px, transparent 1px),
		linear-gradient(to bottom, rgba(31, 157, 132, 0.05) 1px, transparent 1px) !important;
}
[data-theme='light'] .tsd-scanline {
	background: linear-gradient(
		90deg,
		transparent 0%,
		rgba(31, 157, 132, 0.35) 50%,
		transparent 100%
	) !important;
	box-shadow: 0 0 8px rgba(31, 157, 132, 0.2) !important;
	opacity: 0.6 !important;
}
[data-theme='light'] .tsd-corner {
	border-color: #1f9d84 !important;
	opacity: 0.6 !important;
}
[data-theme='light'] .tsd-header {
	border-bottom-color: rgba(31, 157, 132, 0.18) !important;
}
[data-theme='light'] .tsd-title {
	color: #1a1d21 !important;
	text-shadow: none !important;
}
[data-theme='light'] .tsd-title-sub {
	color: #4a5058 !important;
}
[data-theme='light'] .tsd-title-sub::before {
	box-shadow: 0 0 4px rgba(31, 157, 132, 0.4) !important;
}
[data-theme='light'] .tsd-label {
	color: #1a1d21 !important;
}
[data-theme='light'] .tsd-input,
[data-theme='light'] .tsd-textarea,
[data-theme='light'] .tsd-select {
	background-color: rgba(255, 255, 255, 0.8) !important;
	border-color: rgba(31, 157, 132, 0.25) !important;
	color: #1a1d21 !important;
}
[data-theme='light'] .tsd-input::placeholder,
[data-theme='light'] .tsd-textarea::placeholder {
	color: #8a9099 !important;
}
[data-theme='light'] .tsd-input:focus,
[data-theme='light'] .tsd-textarea:focus,
[data-theme='light'] .tsd-select:focus {
	border-color: rgba(31, 157, 132, 0.55) !important;
	background-color: #fff !important;
	box-shadow:
		0 0 0 1px rgba(31, 157, 132, 0.2),
		0 0 12px rgba(31, 157, 132, 0.08) !important;
}
[data-theme='light'] .tsd-select {
	background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 10 10'%3E%3Cpath d='M2 3.5L5 6.5L8 3.5' stroke='%234a5058' stroke-width='1.2' fill='none' stroke-linecap='round'/%3E%3C/svg%3E") !important;
	background-repeat: no-repeat !important;
	background-position: right 10px center !important;
	background-size: 10px 10px !important;
}
[data-theme='light'] .tsd-select option {
	background: #fff;
	color: #1a1d21;
}
[data-theme='light'] .tsd-cover-preview {
	background: rgba(232, 238, 243, 0.6) !important;
	border-color: rgba(31, 157, 132, 0.3) !important;
}
[data-theme='light'] .tsd-cover-preview:hover {
	border-color: rgba(31, 157, 132, 0.55) !important;
	box-shadow: 0 0 10px rgba(31, 157, 132, 0.1) !important;
}
[data-theme='light'] .tsd-cover-placeholder {
	color: #6b7280 !important;
}
[data-theme='light'] .tsd-hint {
	color: #6b7280 !important;
	opacity: 0.8 !important;
}
[data-theme='light'] .tsd-tag-input-wrap {
	background: rgba(255, 255, 255, 0.8) !important;
	border-color: rgba(31, 157, 132, 0.25) !important;
}
[data-theme='light'] .tsd-tag-input-wrap:focus-within {
	border-color: rgba(31, 157, 132, 0.55) !important;
	box-shadow:
		0 0 0 1px rgba(31, 157, 132, 0.2),
		0 0 12px rgba(31, 157, 132, 0.08) !important;
}
[data-theme='light'] .tsd-tag-chip {
	background: rgba(31, 157, 132, 0.08) !important;
	border-color: rgba(31, 157, 132, 0.25) !important;
	color: #17806d !important;
}
[data-theme='light'] .tsd-tag-remove:hover {
	background: rgba(31, 157, 132, 0.15) !important;
}
[data-theme='light'] .tsd-tag-input {
	color: #1a1d21 !important;
}
[data-theme='light'] .tsd-tag-input::placeholder {
	color: #8a9099 !important;
}
[data-theme='light'] .tsd-btn {
	background: rgba(255, 255, 255, 0.6) !important;
	border-color: rgba(31, 157, 132, 0.3) !important;
	color: #1a1d21 !important;
}
[data-theme='light'] .tsd-btn:hover {
	background: rgba(31, 157, 132, 0.1) !important;
	border-color: rgba(31, 157, 132, 0.5) !important;
	box-shadow: 0 0 10px rgba(31, 157, 132, 0.12) !important;
}
[data-theme='light'] .tsd-btn-primary {
	background: rgba(31, 157, 132, 0.15) !important;
	border-color: rgba(31, 157, 132, 0.5) !important;
	color: #17806d !important;
	text-shadow: none !important;
}
[data-theme='light'] .tsd-btn-primary:hover {
	background: #1f9d84 !important;
	border-color: #1f9d84 !important;
	color: #fff !important;
	box-shadow: 0 0 14px rgba(31, 157, 132, 0.25) !important;
}
[data-theme='light'] .tsd-btn-ghost {
	background: transparent !important;
	border-color: rgba(0, 0, 0, 0.15) !important;
	color: #4a5058 !important;
}
[data-theme='light'] .tsd-btn-ghost:hover {
	border-color: rgba(0, 0, 0, 0.25) !important;
	color: #1a1d21 !important;
	background: rgba(0, 0, 0, 0.04) !important;
}
[data-theme='light'] .tsd-btn.active {
	background: rgba(31, 157, 132, 0.12) !important;
	border-color: rgba(31, 157, 132, 0.45) !important;
	color: #17806d !important;
}
[data-theme='light'] .tsd-btn-close:hover {
	color: #1f9d84 !important;
	background: rgba(31, 157, 132, 0.08) !important;
}
[data-theme='light'] .tsd-footer {
	border-top-color: rgba(31, 157, 132, 0.18) !important;
}
[data-theme='light'] .tsd-footer-info {
	color: #6b7280 !important;
}
</style>
