"""Auto-generated by Dweb Studio. Edits may be overwritten."""
from __future__ import annotations

from typing import Any, Dict
from django.http import HttpRequest
from rest_framework.decorators import api_view
from rest_framework.response import Response
import math
from . import models

__DWEB_PROJECT_ID__ = "15f0774d-aadd-469b-b377-7dc78055797d"
__DWEB_PROJECT_NAME__ = "DVideoStudio"
__DWEB_GENERATED_AT__ = "2025-12-31T09:26:43.570Z"

# 提示：健康检查与 echo 默认存在，业务接口由行为流定义生成。
@api_view(["GET"])
def health(request: HttpRequest):
    return Response({"status": "ok", "path": str(request.path)})

@api_view(["GET", "POST"])
def echo(request: HttpRequest):
    data: Dict[str, Any] = {}
    if request.method == "GET":
        data = request.GET.dict()
    else:
        try:
            data = request.data  # type: ignore[assignment]
        except Exception:
            data = {"raw": request.body.decode("utf-8", errors="ignore")}
    return Response({"method": request.method, "data": data})
