# Auto-generated by DBVision
from django.db import models


class ApiProvider(models.TextChoices):
	DEEPSEEK = "deepseek", "DeepSeek"
	GEMINI = "gemini", "Gemini"
	BYTEDANCE = "bytedance", "字节跳动(方舟)"
	CODEX = "codex", "Codex"
	MESHY = "meshy", "Meshy"
	JIMENG_ACCESS_KEY_ID = "jimeng_access_key_id", "即梦 AccessKey ID"
	JIMENG_SECRET_KEY = "jimeng_secret_key", "即梦 SecretAccessKey"


class ApiKeySecret(models.Model):
	"""Local encrypted storage for third-party model API keys.

	Notes:
	- This is NOT a user authentication feature.
	- Encryption-at-rest reduces accidental plaintext leakage, but cannot protect against a fully
	  compromised machine.
	"""

	provider = models.CharField(max_length=32, choices=ApiProvider.choices, unique=True)
	key_encrypted = models.TextField(blank=True, default="")
	key_fingerprint = models.CharField(
		max_length=64,
		blank=True,
		default="",
		help_text="sha256 fingerprint of the plaintext key for UI/status only (not reversible)",
	)
	updated_at = models.DateTimeField(auto_now=True)
	created_at = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = "dweb_api_key_secret"

	def __str__(self) -> str:
		return f"{self.provider} (updated {self.updated_at})"

	@staticmethod
	def _get_fernet():
		"""Build a Fernet encryptor using Django SECRET_KEY-derived bytes."""

		from django.conf import settings
		from django.utils.crypto import pbkdf2

		try:
			from cryptography.fernet import Fernet
		except Exception as e:  # pragma: no cover
			raise RuntimeError(
				"cryptography is required for encrypted API key storage. "
				"Please install it in django-app/requirements.txt"
			) from e

		import base64

		# Fernet expects a 32-byte urlsafe base64 key.
		# Use PBKDF2 (same family as Django password hashing) to derive stable bytes.
		raw = pbkdf2(
			password=str(getattr(settings, "SECRET_KEY", "")),
			salt="dweb-api-key-secret:v1",
			iterations=390000,
			dklen=32,
		)
		fkey = base64.urlsafe_b64encode(raw)
		return Fernet(fkey)

	@staticmethod
	def _fingerprint(plaintext: str) -> str:
		import hashlib

		v = (plaintext or "").strip()
		if not v:
			return ""
		return hashlib.sha256(v.encode("utf-8")).hexdigest()

	def set_plaintext_key(self, plaintext: str) -> None:
		v = (plaintext or "").strip()
		if not v:
			self.key_encrypted = ""
			self.key_fingerprint = ""
			return

		f = self._get_fernet()
		token = f.encrypt(v.encode("utf-8"))
		self.key_encrypted = token.decode("utf-8")
		self.key_fingerprint = self._fingerprint(v)

	def get_plaintext_key(self) -> str:
		token = (self.key_encrypted or "").strip()
		if not token:
			return ""
		try:
			f = self._get_fernet()
			out = f.decrypt(token.encode("utf-8")).decode("utf-8")
			return out
		except Exception:
			return ""
