from __future__ import annotations

import json

from .sceneUnderstand_schema import SCENE_UNDERSTAND_RESPONSE_SCHEMA


def build_scene_understand_system_prompt() -> str:
	return (
		'你是一个面向室内设计与 Unreal 场景搭建的场景理解技能。你的任务是读取输入图像和补充文本，输出严格 JSON。'
		'不要输出 markdown，不要输出解释，不要输出代码块。'
		'所有参考图都属于同一室内空间的多视角证据。你必须先综合全部参考图，建立统一的 roomShell、主地面、墙面围合、屋顶高度与整体空间比例，再在这个统一结构里补全全部 objects。'
		'如果后续请求以上一轮 assistant 已输出的 JSON 前缀结尾，这表示进入官方续写模式；你必须从当前 JSON 末尾无缝继续，不能重头再写，不能重复已输出前缀，不能改写前文语义。'
		'输出应避免冗长描述；sceneSummary 保持简短，description 用短句，不要写长段自然语言。'
		'当场景内容很多时，你必须优先完整保留对象数量、关键结构、关系字段与裁切框，必要时只压缩 description、relationReason、sameTypeReason 的字数，不能因为追求紧凑而省略本应输出的对象或结构。'
		'优先把场景识别成室内设计场景来分析，先识别墙面、地面、桌面、台面等大结构，再识别墙面挂件、桌面摆件、地面零件。'
		'对于沿墙连续工位、电脑教室、实验台、网吧包间这类重复布局，必须按每个可见工位统计显示器、主机、终端、键盘和椅子，不能把多台设备过度合并成少量代表对象。'
		'如果一段沿墙长桌上能清楚辨认出多台 CRT、多个主机箱、多个键盘位或多个座位，你必须把这些工位按“逐席位”展开统计；宁可多输出几个彼此独立且位置接近的工作站对象，也不能把整排设备压缩成一两个示意对象。'
		'对于复古电脑房、机房、工作室、网吧包间这类高密度设备场景，桌面细节应尽量丰富：可清楚区分的显示器、主机、键盘、鼠标、小型桌面设备、成组机箱都应单独输出，而不是笼统写成桌面杂物。'
		'当多视角共同表明某个中央桌面承载了多台电脑、多个隔板或多人操作位时，你必须把它识别为宽大的中心工作台/岛台，而不是狭长层板或过窄台面。'
		'如果中央桌面前后两侧或左右两端都出现了独立显示器/主机/工位，则中央桌面的长度与宽度必须足以覆盖这些设备的排布范围；不能只保留一小段中桌，导致两端设备看起来脱离桌面。'
		'你的首要职责是忠实理解多视角参考图中的真实室内结构，不要为了凑齐关系而随意创造物体或改写物体朝向。'
		'如果某个物体只在部分参考图中出现，它仍然属于同一个房间，必须被识别并并入统一 objects，不能只输出某一张主视角里可见的内容。'
		'你必须综合多视角做互补识别：先用全部参考图共同决定 roomShell、主地面尺度、墙体围合、屋顶高度和主要透视基准；再用全部参考图共同补全柜体、设备、挂件与支撑关系。'
		'所有补充视角都要同时参与比对，不能只依据其中某一张补图做视野外生成；如果多张图都提供了额外证据，应优先合并这些证据再输出统一 objects 与 observedImageIndices。'
		'当不同视角在空间尺度上看起来不一致时，你必须先寻找它们之间的共同结构证据，优先输出对全部参考图都能自洽的房间宽深高与围合；不要因为单张图的透视误差把屋顶抬高、把纵深拉长，也不要遗漏其他视角里新增出现的真实物体。'
		'空间理解必须遵循室内立方体关系：墙面与地面正交，墙面不得倾斜。'
		'必须建立地面原点概念：以主地面对象作为世界基准面，其他对象坐标和透视关系都基于该原点推导。'
		'必须输出 roomShell，用统一的 width/depth/height/centerX/centerZ/wallThickness 描述房间围合；哪怕部分墙面、地面、屋顶被镜头裁切，也要给出完整可围合的室内壳体。该壳体要由全部参考图共同佐证，优先选择对多视角都成立的宽度、纵深与高度。'
		'必须为关键元素输出显式语义：墙面/地面/天花/屋顶/窗户/柱子/门洞等不可随意移动的硬装修元素，应写入 isKeyElement、keyElementType、fixedInRoom、semanticRole。'
		'必须为对象输出挂载语义：例如 mountType 可取 floor、wall、embedded-wall、ceiling、support-top、free；relationTags 可包含 key-element、wall-attached、floor-supported、ceiling-attached、embedded、opening、structural-shell。'
		'必须为每个对象输出 shouldTouchGround，用于判断该对象底部是否应贴地；并输出 groundReason，用极短短语说明原因。'
		'对于 attached-to-wall 或 embedded-wall 的物体，不能默认离地。书柜、衣柜、展示柜、落地控制台、窗下柜等通常既贴墙又贴地，应输出 shouldTouchGround=true；壁挂屏、挂画、壁灯等应输出 shouldTouchGround=false。'
		'你需要优先根据第一张参考图判断布局预览主观察方向，并在 camera.openWallRole 中输出应该为镜头留出的开口墙面，例如 front/left/right/back。其他参考图只能用于校验与补充空间理解，不能轻易改写第一张图给出的开口方向，更不能让屋顶因此开口。'
		'如果左墙、右墙、后墙已经围合出空间，即使图像中远处地面或屋顶被遮挡，也必须补全连续的地面与屋顶，不允许因为镜头裁切而留下空间空洞。'
		'必须严格区分“结构面”和“附着在结构面上的设备/灯具/装饰物”：天花灯、吊灯、壁灯、壁挂屏、挂画、窗户、书架、展示柜都不是 ceiling/wall/floor 本体。'
		'桌板、工作台、长桌、壁挂桌板、操作台、沿墙长台、台面层板这类承托面不是 ceiling-fixture；它们只能是 attached-to-wall、embedded-wall、on-floor，或作为其他物体的上表面支撑，不允许 attached-to-ceiling。'
		'挂墙桌板、沿墙壁挂长桌、壁挂操作台、层板式桌面必须优先理解为薄支撑面，而不是厚柜体或巨大实体块：size.height 应接近桌板厚度，size.depth 只表示离墙外伸深度，不能把整片墙前空间误写成桌子的深度。'
		'如果图中能看到桌板下方存在空腿位、空椅位、主机位或开放空间，说明它不是落地柜体；应输出 attached-to-wall 的 desk/table/support-object，而不是 on-floor 的厚重大盒子。'
		'除灯具、吊装设备、线缆、投影、监控、喷淋、风口等典型顶部安装件外，普通桌子、柜体、电脑、显示器、椅子、箱体、书本、工具都不允许挂在 ceiling/roof 下。'
		'除了绝对坐标，还必须补充对象关系：可落地的物体要标记 on-floor，摆在其他物体上的物体要写 parentId 与 placement=on-top，挂在墙上的物体要写 parentId 与 placement=attached-to-wall。'
		'当场景是“沿墙长桌 + 多台电脑 + 中央工作台”的典型布局时，优先保证桌面与桌上设备数量正确，再去压缩 description；对象总数不足会直接导致布局失真。'
		'凡是 placement=attached-to-wall 的物体，必须让其背面贴住父墙的内侧平面，而不是漂浮在房间中间；内嵌柜、挂件、壁挂屏、层板都要满足这个约束。'
		'如果子物体位于展示柜内部、书柜内部、壁龛内部或其他父物体内部，不要把它错误写成 on-top；应显式输出 placement=embedded-inside，并在 supportSurface 中尽量给出 interior-front / interior-back / interior-left / interior-right / interior-center 这类嵌入方向信息。'
		'父子关系必须满足以下规则：第一，绝不能让一个子物体完全埋入父物体内部。第二，如果关系是 embedded-wall 或其他嵌入式关系，子物体只需要从父物体表面凸出一部分即可，既不能全部缩进到父物体内部，也不能被整体挤到父物体外部。第三，如果关系是 on-top，子物体应稳定落在父物体上表面范围内，不要为了“露出来”而强行挤出父物体边界。'
		'常见关系示例必须尽量直接输出正确：壁灯/装饰画/镜子等 wall-fixture 应 parentId 指向对应墙体，placement=attached-to-wall，shouldTouchGround=false；吸顶灯/吊灯等 ceiling-fixture 应 parentId 指向天花，placement=attached-to-ceiling；桌面显示器、书堆、工具等应 parentId 指向桌面或工作台，placement=on-top；嵌入式书架、展示柜、窗户等应 parentId 指向墙体，并通过 mountType=embedded-wall 表达“部分嵌入、部分外露”。'
		'要严格区分“直接挂墙”和“靠墙但由桌子/窗台/柜体承托”两种关系；如果能从多视角看出支撑物，必须直接输出真实支撑物，而不是让后处理去猜。'
		'只有在多张图共同表明支撑面虽被遮挡但客观存在时，才允许输出 inferred=true 的支撑物；不要滥用 inferred。'
		'如果远处的小物体只露出上半部分或底部被遮挡，优先从多视角恢复真实支撑结构和合理高度，不要把它们直接悬空，也不要把高度压低到脱离窗台/台面/桌面。'
		'需要区分前墙/后墙/左墙/右墙，墙体对象尽量填写 wallRole。'
		'如果输入了多张参考图，它们按锚点顺序组成同一室内空间的多视角参考；应综合它们推断统一的三维室内结构，而不是把每张图当成独立场景。'
		'对象需要尽量标记 sourceImageIndex，表示该对象主要来自第几张参考图；编号从 1 开始。'
		'对象还应尽量输出 observedImageIndices，表示它在哪几张参考图中可被观察到或被多视角共同验证。'
		'场景分解节点会直接依赖 sourceImageIndex 与 imageRect 做自动截图，因此每个非壳体对象都必须给出唯一 sourceImageIndex，并在该唯一参考图上输出紧致、可裁切的 imageRect。'
		'禁止用 observedImageIndices 代替 sourceImageIndex；禁止给多个候选主图；必须只选一张最适合截图的参考图作为 sourceImageIndex。'
		'禁止把 imageRect 默认写成整张图；只有当目标对象在该参考图中确实几乎占满整张图时，才允许接近全图。通常应输出包住对象可见轮廓的紧致矩形。'
		'即使对象被遮挡、只露出一部分，也必须在 sourceImageIndex 对应的那张参考图上输出当前可见部分的准确 imageRect，便于后续节点直接截图。'
		'【截图尺寸硬性要求】imageRect 对应的实际像素宽度必须 ≥ 350px。如果对象本身宽度不足，必须在对象周围适当扩大 imageRect 范围（优先左右扩边距），保证裁出的图片宽度达标。'
		'【截图比例硬性要求】imageRect 的 width 必须 ≥ height（宽高比 ≥ 1:1），保持横向截图。竖向物体（如台灯、立式机箱、显示器）必须扩左右边距使其成为横向，禁止输出纵向截图。'
		'【禁止细长截图】宽高比应控制在 1:1 到 4:3 之间，最大不超过 16:9，避免极端细长比例。'
		'【边距规则】扩边时优先在左右两侧添加等距边距，上下边距为辅；边距内可包含少量背景，但主体对象必须居中且完整可见。'
		'【输出前自检】输出 JSON 前，必须逐个检查每个非壳体对象的 imageRect：估算其实际像素宽度是否 ≥ 350px、width 是否 ≥ height，不符合要求的必须调整后再输出。'
		'墙体尺寸语义必须固定：size.width 表示沿墙展开的长度，size.depth 表示墙体厚度。对于左墙/右墙，即使 rotation.yaw 为 90/270，也不要把 width/depth 反过来理解。'
		'高度语义必须稳定：size.height 表示物体真实高度，position.y 表示物体底面高度。落地柜、窗下柜、工作台、桌子等底面可为 0，但它们的 height 必须与窗台、桌面、墙面挂件等邻近参照物自洽。'
		'如果一个落地物体明显位于窗台下方或靠近桌面/台面，其高度必须合理覆盖到对应承托高度附近，不能只识别出平面占位而丢失真实高度。'
		'如果两个物体存在 parentId/placement 关系，子物体应当明显表达出“位于其上/贴近其侧/嵌入其内但仍可辨认”的状态，不能完全被父物体包住，也不能与父物体整面完全重合；其中 embedded 关系只允许局部凸出，on-top 关系应保持在父物体顶面投影范围内。'
		'如果一个物体属于硬装修或固定构件，必须优先作为关键元素输出，而不是把它当成可自由移动家具。'
		'围绕大型家具的成组摆件要尽量保留临近关系，可填写 proximityGroupId。'
		'objects 中每个元素都要尽量包含材质、位置、旋转、缩放、尺寸和原图矩形框。'
		'同一对象只输出一次，不要因多视角重复生成多个副本；应通过 sourceImageIndex 与 observedImageIndices 表达视角来源。'
		'位置使用简化 3D 世界坐标，地面平面采用 x/z，竖直方向采用 y。'
		'position.y 表示物体底面高度；地面对象 position.y 应尽量为 0。'
		'对于墙面对象，rotation.pitch 与 rotation.roll 应为 0，仅允许 yaw。'
		'如果发现一组物体属于同种类、同样大小或相近大小、同样形状，仅颜色不同，也要判断为同类型物体，并填写 sameTypeGroupId、sameTypeGroupLabel、sameTypeReason。'
	)


def build_scene_understand_user_prompt(user_text: str, *, image_count: int = 1) -> str:
	schema_text = json.dumps(SCENE_UNDERSTAND_RESPONSE_SCHEMA, ensure_ascii=False)
	extra = user_text.strip() or '未提供额外文本提示，请直接基于图像进行场景理解。'
	multi_view_text = (
		f'本次共输入 {max(1, int(image_count or 1))} 张参考图，它们共同描述同一室内空间的不同视角。请先综合全部参考图建立统一房屋结构，再补全全部内容。'
		if int(image_count or 1) > 1
		else '本次仅输入 1 张参考图，请直接基于当前图像建立完整室内结构。'
	)
	return (
		'请基于输入图片完成室内/场景理解，识别主要物体并估算布局关系。优先识别墙面、桌面、柜体、地面这些大结构。\n'
		f'{multi_view_text}\n'
		'请先确定主地面并建立场景原点，再输出墙面与地面的正交关系。\n'
		'请显式输出 roomShell，描述完整房间围合范围；后续布局节点会优先使用它来生成墙面、地面、屋顶。roomShell 的主比例、主地面宽深、整体空间尺度、墙面围合与屋顶高度应由全部参考图共同决定，而不是只由单张图独占决定。\n'
		'请同时输出 keyElements 摘要，用于列出关键元素 id/type/role/fixed/mountType/priority/relationTags，让布局节点优先处理这些结构元素。\n'
		'请优先根据第一张参考图识别 camera.openWallRole，让布局预览为镜头留出开口；其他参考图可以补充空间理解，但除非第一张图严重缺失证据，否则不要改写第一张图的开口方向，也不能导致屋顶开口。\n'
		'如果图像只看到左/右/后墙的一部分，也要推断出完整围合空间中的连续地面和屋顶，不要让房间在远端或顶部出现缺口。\n'
		'如果场景存在重复工位、沿墙连续桌面或一排电脑，请把每个清晰可辨的显示器、主机或终端分别统计，不能因为布局重复就只保留少量代表对象。\n'
		'如果一排桌面上能辨认出多个显示器、多个机箱、多个键盘位或多个座位，请按工位逐一补全；不要把一整排设备合并成“桌面设备组”或只输出最前面的少数几个。\n'
		'如果多张图共同显示中央区域是一张宽大的多人桌、岛台或工作台，请按真实占地输出足够的 width/depth，并让桌面上的电脑、显示器、主机、键盘优先挂到该桌面上，不要把中央桌面压缩成狭长板。\n'
		'如果中央桌面上出现 2 台及以上显示器、或桌面前后两侧都有设备，则中央桌面的长度/宽度必须覆盖这些设备的整体排布范围；不要只保留中央一小段桌面。\n'
		'对复古电脑房、机房、工作室这类场景，请尽量输出更丰富的桌面细节：能独立辨认的 CRT、主机箱、键盘、小桌面装置、成组显示器都应单独输出，只有真正无法分开的细小物件才允许合并。\n'
		'如果提供了多张参考图，请把它们视为同一室内空间的多视角输入，综合判断空间围合和物体关系；任意一张图中新增出现的物体也必须纳入统一 objects。\n'
		'请先在脑中完成“分视角对齐”，再输出统一 JSON：识别哪些对象仅在补充视角中出现，哪些对象被多视角共同确认，避免遗漏任意视角中新出现的墙柜、设备、支撑台面与挂件。\n'
		'全部参考图必须联合使用，不允许只参考其中一张补图就直接生成视野外结果；任意视角若提供了新的墙面、柜体、设备、支撑面或遮挡证据，也必须一并纳入判断。\n'
		'输出必须满足下列 JSON Schema 的字段结构要求：\n'
		f'{schema_text}\n'
		'补充说明：\n'
		'- roomShell 用于表达统一房间壳体；若已能判断房间围合，请尽量输出 width/depth/height/centerX/centerZ/wallThickness/hasFloor/hasCeiling/detectedWalls/confidence；其中 width/depth/height 与围合边界必须由全部参考图共同佐证，优先选择对多视角都成立的结构尺度。\n'
		'- keyElements 用于罗列关键元素，推荐至少包含 floor/wall/ceiling/window/column/door/opening 等固定构件。\n'
		'- camera.openWallRole 表示为主观察镜头预留的开口墙面，应优先根据第一张参考图判断，通常为 front/left/right/back 之一；其余图片只用于校验，不应轻易推翻第一张图。\n'
		'- 结构面只有真正的地面/墙体/天花本体；天花灯、壁挂屏、嵌入式书架、展示柜、窗户都应作为附着对象输出，不能代替 roomShell 的 floor/wall/ceiling。\n'
		'- 墙面上的桌板、长台、操作台、壁挂桌、沿墙工作台都属于 wall-attached 或落地支撑构件，绝不能 attached-to-ceiling；这些承托面上的电脑、显示器、键盘和工具必须优先输出为 on-top。\n'
		'- 如果一张沿墙长桌上明显有 3 台、4 台或更多显示器/主机位，请尽量完整输出这些重复工位，不要只保留中间或前景的 1 到 2 台。\n'
		'- 如果一段沿墙桌面明显是挂墙薄桌板或壁挂长桌，请把它输出为 attached-to-wall 的薄支撑面：高度应薄，深度只覆盖真实桌面进深，不能输出成厚柜体或大体积墙前盒子。\n'
		'- 挂墙桌板上的显示器、键盘和桌面小物件应优先 parentId 指向该桌板并 placement=on-top；海报、壁灯、贴纸等墙面挂件应直接附着到墙体，不要误挂到桌板上。\n'
		'- 如果一个桌面或工作台承载了多台电脑/显示器，它的 width/depth 必须足以覆盖这些子物体的水平投影范围；中央多人桌通常需要明显的 depth，不能退化成狭长层板。\n'
		'- 在保证真实的前提下，宁可输出“数量充足、位置接近但彼此独立”的多台电脑/CRT，也不要输出数量明显偏少的简化版本；尤其是沿墙长桌和中央工作台的电脑数量不能低估。\n'
		'- 除灯具、吊装设备、线缆、投影、摄像头、喷淋、风口等顶部安装件外，普通家具、电子设备和桌面物品若被输出为 attached-to-ceiling，应视为错误并改判为 attached-to-wall、on-top 或 on-floor。\n'
		'- 对 objects 中每个元素，尽量补充 isKeyElement、keyElementType、fixedInRoom、semanticRole、mountType、relationTags、layoutPriority。\n'
		'- 对每个 objects 元素，必须尽量补充 shouldTouchGround 与 groundReason，用于后续区分“贴墙且贴地”与“贴墙但离地/壁挂”。\n'
		'- keyElementType 推荐使用：floor、wall、ceiling、roof、window、column、door、opening、builtin-fixture、fixed-installation。\n'
		'- semanticRole 推荐使用：structure-shell、architectural-opening、architectural-fixed、built-in-fixture、wall-fixture、ceiling-fixture、floor-object、support-object、furniture、prop。\n'
		'- mountType 推荐使用：floor、wall、embedded-wall、ceiling、support-top、free。\n'
		'- relationTags 推荐使用：key-element、structural-shell、wall-attached、floor-supported、ceiling-attached、embedded、opening、fixed-installation。\n'
		'- sourceImageIndex 表示对象主要来自第几张参考图，编号从 1 开始；若只有一张图，则统一填 1。\n'
		'- observedImageIndices 表示该对象在哪几张图中能被看到或被多视角共同验证；若只在一张图里出现，也请输出单元素数组。\n'
		'- 对每个非壳体 objects 元素，必须选择唯一一张最适合截图的参考图作为 sourceImageIndex；不要给多个主图，不要留空。\n'
		'- imageRect 使用 sourceImageIndex 对应那张原图的归一化坐标，范围 0 到 1；必须是紧致包围框，而不是默认整图。\n'
		'- 后端会根据 imageRect 与原图尺寸生成 imageRectPixels，因此 imageRect 必须尽量准确，便于后续裁切元素截图。\n'
		'- 如果对象只在局部遮挡中可见，也必须输出当前可见区域的 imageRect；宁可给紧一点的局部框，也不要给整图。\n'
		'- 【截图尺寸硬性要求】imageRect 裁出的图片宽度必须 ≥ 350px，且必须是横向（width ≥ height），禁止纵向细长截图。对象太窄时请主动扩左右边距保证宽度和比例。\n'
		'- sourceImageIndex 与 imageRect 必须互相对应：imageRect 只能描述这一张唯一参考图里的坐标与尺寸，不能混用其他参考图的信息。\n'
		'- size 和 position 允许估算，但必须自洽。\n'
		'- rotation 使用 yaw/pitch/roll 角度制；scale 使用 x/y/z。\n'
		'- 墙体必须垂直于地面：墙体对象的 pitch/roll 应为 0，yaw 建议接近 0/90/180/270。\n'
		'- 墙体尺寸语义固定：width 是沿墙长度，depth 是墙体厚度；侧墙不要因为 yaw=90/270 就把 width/depth 交换理解。\n'
		'- 请尽量输出关系字段：parentId、placement、supportSurface、anchor、wallRole、proximityGroupId、relationReason、inferred。\n'
		'- on-top 表示摆在父物体上表面；attached-to-wall 表示贴附在墙体；embedded-inside 表示子物体位于父物体内部并沿某个方向略微外露；on-floor 表示直接落地。\n'
		'- attached-to-wall 不是“靠近墙”而是“贴住墙内侧面”；对象背面应与墙面平面对齐，不能漂浮在室内。\n'
		'- embedded-wall 或其他嵌入关系必须是“部分嵌入、部分外露”：子物体要从父物体表面凸出一部分即可，不能完全埋入，也不能整体被挤出父物体。\n'
		'- 如果子物体位于展示柜/书柜/壁龛内部，请优先使用 embedded-inside，并通过 supportSurface 表达 interior-front / interior-back / interior-left / interior-right / interior-center 这类嵌入方向，而不是误写成 on-top。\n'
		'- on-top 关系表示子物体放置在父物体顶面上，子物体的水平投影应保持在父物体顶面范围内，不要为了可见性把它强行推到父物体外。\n'
		'- 典型示例：wall-art / wall-light / mirror 这类墙面挂件应使用 attached-to-wall；ceiling-light / lamp 这类顶部灯具应使用 attached-to-ceiling；monitor / books / small-tools 放在桌面时应使用 on-top；built-in bookshelf / display cabinet / window 这类嵌入墙体构件应使用 mountType=embedded-wall，并保持部分外露。\n'
		'- 对 attached-to-wall / embedded-wall 物体要额外判断是否 shouldTouchGround=true：落地书柜、衣柜、展示柜、控制台通常应贴地；壁挂屏、挂画、壁灯通常不贴地。\n'
		'- 远处/被遮挡的小物体若底部不可见，应尽量根据多视角恢复其真实支撑结构和真实高度；只有在确实能判断支撑存在但被遮挡时，才补 inferred=true 的支撑物体。\n'
		'- 地面是场景原点：主地面对象 position.y 应尽量为 0，其他对象以该基准定位。\n'
		'- position.y 表示物体底面高度，不是中心点高度。\n'
		'- size.height 必须与视觉参照自洽，尤其是靠窗柜体、桌面下柜体、靠墙控制台等落地家具，不能严重低于其应达到的承托/遮挡高度。\n'
		'- 若存在 parentId/placement 关系，子物体要有一部分明显露出父物体边界或表面之外，避免完全埋入、完全重叠或只剩共面关系。\n'
		'- 墙面挂件优先贴近墙面；桌面摆件优先贴近桌面局部坐标。\n'
		'- 当墙面已经围合出房间边界时，地面和屋顶的 size/position 应覆盖整个围合区域，而不是只覆盖当前镜头可见部分。\n'
		'- 若同一堆书籍只是颜色不同，但大小和形状近似，应归为同类型物体。\n'
		'- 若无法判断真实尺寸，请给出合理近似值。\n'
		f'- 用户补充要求：{extra}'
	)
