# Generated by ChatGPT for codex_bridge initial schema
from __future__ import annotations

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("provider", models.CharField(default="codex", max_length=50)),
                ("model_name", models.CharField(default="", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("failed", "Failed"), ("closed", "Closed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("provider_thread_id", models.CharField(blank=True, max_length=120)),
                ("cwd", models.CharField(blank=True, max_length=500)),
                ("approval_policy", models.CharField(blank=True, max_length=60)),
                ("last_turn_status", models.CharField(blank=True, max_length=60)),
                ("sandbox_policy", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "codex_bridge_chat_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User"), ("assistant", "Assistant"), ("tool", "Tool")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("item_type", models.CharField(blank=True, max_length=60)),
                ("stream_phase", models.CharField(blank=True, max_length=40)),
                ("tool_name", models.CharField(blank=True, max_length=120)),
                ("provider_item_id", models.CharField(blank=True, max_length=120)),
                ("command", models.JSONField(blank=True, default=dict)),
                ("file_changes", models.JSONField(blank=True, default=list)),
                ("approval_request", models.JSONField(blank=True, default=dict)),
                ("usage", models.JSONField(blank=True, default=dict)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="codex_bridge.chatsession"),
                ),
            ],
            options={
                "db_table": "codex_bridge_chat_message",
                "ordering": ["created_at"],
            },
        ),
    ]
